// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBookApp.Data;

#nullable disable

namespace PhoneBookApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316085734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneBookApp.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Zenica"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Zagreb"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Split"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            Name = "Dubrovnik"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Name = "Rijeka"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            Name = "Novi Sad"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 3,
                            Name = "Beograd"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            Name = "Niš"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 3,
                            Name = "Kragujevac"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 4,
                            Name = "Wien"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 4,
                            Name = "Graz"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 4,
                            Name = "Linz"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 4,
                            Name = "Salzburg"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 5,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 5,
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 5,
                            Name = "München"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 5,
                            Name = "Köln"
                        });
                });

            modelBuilder.Entity("PhoneBookApp.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1985, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 1,
                            CountryId = 1,
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            Gender = 1,
                            LastName = "Doe",
                            PhoneNumber = "123/456-789"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 5,
                            CountryId = 2,
                            Email = "janedoe@example.com",
                            FirstName = "Jane",
                            Gender = 0,
                            LastName = "Doe",
                            PhoneNumber = "987/654-321"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1980, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 10,
                            CountryId = 3,
                            Email = "marksmith@example.com",
                            FirstName = "Mark",
                            Gender = 1,
                            LastName = "Smith",
                            PhoneNumber = "555/555-555"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1985, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 16,
                            CountryId = 4,
                            Email = "ibrahim@example.com",
                            FirstName = "Ibrahim",
                            Gender = 1,
                            LastName = "Hasić",
                            PhoneNumber = "123/456-789"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1990, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 3,
                            CountryId = 1,
                            Email = "amira@example.com",
                            FirstName = "Amira",
                            Gender = 0,
                            LastName = "Džanić",
                            PhoneNumber = "987/654-321"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1980, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 8,
                            CountryId = 2,
                            Email = "hasan@example.com",
                            FirstName = "Hasan",
                            Gender = 1,
                            LastName = "Selimović",
                            PhoneNumber = "555/555-555"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1992, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 14,
                            CountryId = 4,
                            Email = "elma@example.com",
                            FirstName = "Elma",
                            Gender = 0,
                            LastName = "Begović",
                            PhoneNumber = "321/654-987"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1989, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 20,
                            CountryId = 5,
                            Email = "mirza@example.com",
                            FirstName = "Mirza",
                            Gender = 1,
                            LastName = "Kovačević",
                            PhoneNumber = "123/321-456"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1995, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 13,
                            CountryId = 4,
                            Email = "maja@example.com",
                            FirstName = "Maja",
                            Gender = 0,
                            LastName = "Avdagić",
                            PhoneNumber = "654/987-321"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1987, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CityId = 7,
                            CountryId = 2,
                            Email = "nedim@example.com",
                            FirstName = "Nedim",
                            Gender = 1,
                            LastName = "Salkanović",
                            PhoneNumber = "987/123-654"
                        });
                });

            modelBuilder.Entity("PhoneBookApp.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("PhoneBookApp.Models.City", b =>
                {
                    b.HasOne("PhoneBookApp.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PhoneBookApp.Models.Contact", b =>
                {
                    b.HasOne("PhoneBookApp.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PhoneBookApp.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PhoneBookApp.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
